spring.application.name=limited-goods

spring.datasource.url=jdbc:postgresql://localhost:5432/limited_goods
spring.datasource.username=limited_goods
spring.datasource.password=limited_goods

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

management.endpoints.web.exposure.include=health,prometheus
